language: python
cache: pip
python:
- '3.6'
install:
- git fetch --tags --depth=500
- pip install 'pytest>=3.6' --force-reinstall
- pip install pytest-cov codecov requests
- pip install -r ./requirements.txt
script:
- pytest  tests/ --cov-report term --cov=./zvdata
after_success:
- codecov
deploy:
  provider: pypi
  user: foolcage
  password:
    secure: DkbAgsUR06c2QgT6s0IZu4pGkq4MJtAue27vNvOYXhD9YwmqqXsHzDMUxRvKzNYOX9Pa+GiMFbHJOeAEOvTWQDWdzniSlOiqzy31gmA25oKaS53maGUBdoBZuaEKwgyAlc2SyReZKoADB2NbNLQ3cBNgPd2BN0iDwRDyZbfFXZ5Xqp/Swhugia+1bLECHZ0PjrtSHio4RAuaQB72Aw9Luq5TCdnVn4ahqP5ByyIaAiU7E0KzifDaZBzRtVWiZ6egHspXQDvQVdGzZI5vgnfaDMAQzWBliP/+WhxerEr0wKY7mcX//v3MvnfyzrqdbKeg/AbWjQ3bu1hhTXgIJyi3S1JXvjPq+0UvvJhjLau4zweuUVz66HBmYFkj/VugnRbA/V5R0AxtNhOBuiG+ZzUKUta+ICD2jDt/uB6eHWVJxu0B107M85GLtVK9KK8x78+KNOQKiINRC0fyBUD2Skku7kLv+wU+x8kFsvx22hbluk10Rz3q6iC7yIXMO07M+PQ1tLQCSNvqpQWdkntNMKjKPT6xw/vhJZIXX8MijKQ/zoRQaE/fPp2IkQTT1IXuOe/MIz3ixp0a1FRxYxixhYVJwJwaRKrb6gErlc6Az4pauiHPHwUjzTTXiySqDiHCV6CX6rG6ohVvi4ZgQV4FFI1BMeHd21fPsEn8C8Im3k6EdPM=
  on:
    tags: true
notifications:
  email:
    recipients:
    - 5533061@qq.com
